service:
  name: chosun-serverless-tutorial
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline-s3
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  first:
    handler: first.hello
    events:
      - s3: 
          bucket: photo
          event: s3:ObjectCreated:*

custom:
  serverless-offline-s3:
    endpoint: http://0.0.0.0:9000
    accessKey: AKIAIOSFODNN7EXAMPLE
    secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY